### ISSUE TITLE
Issue about DRY

### ISSUE THREAD

**Issue by redmarverick** [Alejuda/TODO-List#9]
https://github.com/Alejuda/TODO-List/blob/baf0ed627eb3d64f6d6c429c92c99d67e74f9807/src/addAndRemove.js#L16

The code makes use of helper functions to avoid repeating code, such as JSON.parse(localStorage.getItem('tasks-list')) which is used multiple times. However, there are some sections of code that could be refactored to reduce duplication, such as the logic for updating the tasks-list array after a task is removed.

**Comment by Alejuda** [comment]
Thank's for your recommendation Victor! I will change this 👌🏼
